module.exports.columns = [
    {
        title: '课程id',
        dataIndex: 'course_id',
        editable: true,
        notNull: true,
        type: 'int',
        templateIndex: 0,
    },
    {
        title: '课程名称',
        dataIndex: 'course_name',
        editable: false,
        notNull: false,
        type: 'char',
        templateIndex: 1,
        sourceTable: 'course_tbl',
        primaryKey: 'course_id',
        foreignKey: 'course_id',
    },
    {
        title: '课程类型',
        dataIndex: 'course_type',
        editable: false,
        notNull: false,
        type: 'char',
        templateIndex: 2,
        sourceTable: 'course_tbl',
        primaryKey: 'course_id',
        foreignKey: 'course_id',
    },
    {
        title: '上课专业id',
        dataIndex: 'specialityId',
        editable: true,
        notNull: false,
        type: 'int',
        templateIndex: 3,
    },
    {
        title: '上课专业名称',
        dataIndex: 'specialityName',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 4,
    },
    {
        title: '工号',
        dataIndex: 'job_id',
        editable: true,
        notNull: true,
        type: 'int',
        templateIndex: 5,
    },
    {
        title: '姓名',
        dataIndex: 'teacher_name',
        editable: false,
        notNull: false,
        type: 'char',
        templateIndex: 6,
        sourceTable: 'teacher_tbl',
        primaryKey: 'job_id',
        foreignKey: 'job_id',
    },
    {
        title: '上课人数',
        dataIndex: 'student_num',
        editable: true,
        notNull: false,
        type: 'int',
        templateIndex: 7,
    },
    {
        title: '时间',
        dataIndex: 'time',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 8,
    },
    {
        title: '课程学分',
        dataIndex: 'credit',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 9,
    },
    {
        title: '效益系数',
        dataIndex: 'benefit_coefficient',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 10,
    },
    {
        title: '备注',
        dataIndex: 'remark',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 11,
    },
]

module.exports.rules = {
    tableType: '课程教学',
    itemColumnName: 'course_name',
    editable: false,
    sourceTable: 'course_tbl',
    primaryKey: 'course_id',
    foreignKey: 'course_id',
    ruleColumnName: 'course_type',
    columns: [
      {title: "课程类型", dataIndex: "course_type", editable: true},
      {title: "工作量", dataIndex: "workload", editable: true},
      {title: "绩效", dataIndex: "performance_score", editable: true},
      {title: "奖金", dataIndex: "bonus", editable: true},
    ],
    Chinese2English: {
      '课程学分': 'credit',
      '上课人数': 'student_num',
      '效益系数': 'benefit_coefficient',
    }
  }
// mock语句
// insert into textbook(textbook_type,textbook_name,textbook_publisher,director_job_id,member,publish_time,is_excellent,remark,performance_scroe,bonus,workload) values('国家级','数据结构','西北大学出版社',20130069,'cf','2019/01/01','是','无备注',1,1,1);

