module.exports.columns = [
    {
        title: '毕设名',
        dataIndex: 'gradproject_name',
        editable: true,
        notNull: true,
        type: 'char',
        templateIndex: 0,
    },
    {
        title: '毕设类型',
        dataIndex: 'gradproject_type',
        editable: true,
        notNull: true,
        type: 'char',
        templateIndex: 1,
    },
    {
        title: '毕业设计时间',
        dataIndex: 'gradproject_time',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 2,
    },
    {
        title: '学分',
        dataIndex: 'credit',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 3,
    },
    {
        title: '学生学号',
        dataIndex: 'student_id',
        editable: true,
        notNull: false,
        type: 'int',
        templateIndex: 4,
    },
    {
        title: '学生姓名',
        dataIndex: 'student_name',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 5,
    },
    {
        title: '学生专业',
        dataIndex: 'student_major',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 6,
    },
    {
        title: '学生年级',
        dataIndex: 'student_grade',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 7,
    },
    {
        title: '指导老师工号',
        dataIndex: 'job_id',
        editable: true,
        notNull: false,
        type: 'int',
        templateIndex: 8,
    },
    {
        title: '指导老师姓名',
        dataIndex: 'teacher_name',
        editable: false,
        notNull: false,
        type: 'char',
        templateIndex: 9,
        sourceTable: 'teacher_tbl',
        primaryKey: 'job_id',
        foreignKey: 'job_id',
    },
    {
        title: '企业指导老师编号',
        dataIndex: 'corporate_mentor_id',
        editable: true,
        notNull: false,
        type: 'int',
        templateIndex: 10,
    },
    {
        title: '备注',
        dataIndex: 'remark',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 11,
    },
]

// mock语句
// insert into textbook(textbook_type,textbook_name,textbook_publisher,director_job_id,member,publish_time,is_excellent,remark,performance_scroe,bonus,workload) values('国家级','数据结构','西北大学出版社',20130069,'cf','2019/01/01','是','无备注',1,1,1);

