module.exports.columns = [
  {
    title: '名称',
    dataIndex: 'project_name',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 0,
  },
  {
    title: '类型',
    dataIndex: 'project_type',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 1,
  },
  {
    title: '获批时间',
    dataIndex: 'approve_time',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 2,
  },
  {
    title: '所属一级学科',
    dataIndex: 'project_major',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 3,
  },
  {
    title: '参与学生人数',
    dataIndex: 'participation_number',
    editable: true,
    notNull: false,
    type: 'int',
    templateIndex: 4,
  },
  {
    title: '状态（在研/结题）',
    dataIndex: 'project_status',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 5,
  },
  {
    title: '中期检查结果',
    dataIndex: 'mid_check_result',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 6,
  },
  {
    title: '结题检查结果',
    dataIndex: 'end_check_result',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 7,
  },
  {
    title: '获批经费（元）',
    dataIndex: 'appropriation_approve',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 8,
  },
  {
    title: '项目级别',
    dataIndex: 'project_level',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 9,
  },
  {
    title: '负责人学号',
    dataIndex: 'director_id',
    editable: true,
    notNull: false,
    type: 'int',
    templateIndex: 10,
  }, 
  {
    title: '负责人姓名',
    dataIndex: 'director_name',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 11,
  },
  {
    title: '负责人专业',
    dataIndex: 'director_major',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 12,
  },
  {
    title: '负责人年级',
    dataIndex: 'director_grade',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 13,
  }, 
  {
    title: '成员1学号',
    dataIndex: 'member1_id',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 14,
  },
  {
    title: '成员1姓名',
    dataIndex: 'member1_name',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 15,
  },
  {
    title: '成员1专业',
    dataIndex: 'member1_major',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 16,
  }, 
  {
    title: '成员1年级',
    dataIndex: 'member1_grade',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 17,
  },
  {
    title: '成员2学号',
    dataIndex: 'member2_id',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 18,
  },
  {
    title: '成员2姓名',
    dataIndex: 'member2_name',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 19,
  }, 
  {
    title: '成员2专业',
    dataIndex: 'member2_major',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 20,
  },
  {
    title: '成员2年级',
    dataIndex: 'member2_grade',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 21,
  }, 
  {
    title: '指导教师姓名',
    dataIndex: 'teacher_name',
    editable: false,
    notNull: false,
    type: 'char',
    templateIndex: 22,
    sourceTable: 'teacher_tbl',
    primaryKey: 'mentor_job_id',
    foreignKey: 'job_id',
  },
  {
    title: '指导教师工号',
    dataIndex: 'mentor_job_id',
    editable: true,
    notNull: true,
    type: 'int',
    templateIndex: 23,
  },
  {
    title: '备注',
    dataIndex: 'remark',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 24,
  },
  {
    title: '绩效计分',
    dataIndex: 'performance_scroe',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 25,
  },
  {
    title: '奖金',
    dataIndex: 'bonus',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 26,
  },
  {
    title: '工作量',
    dataIndex: 'workload',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 27,
  }, 
]