module.exports.columns = [
    {
        title: '实习id',
        dataIndex: 'internship_id',
        editable: true,
        notNull: true,
        type: 'int',
        templateIndex: 0,
    },
    {
        title: '实习名称',
        dataIndex: 'internship_name',
        editable: true,
        notNull: true,
        type: 'char',
        templateIndex: 1,
    },
    {
        title: '实习类型',
        dataIndex: 'internship_type',
        editable: true,
        notNull: true,
        type: 'char',
        templateIndex: 2,
    },
    {
        title: '实习性质',
        dataIndex: 'internship_nature',
        editable: true,
        notNull: true,
        type: 'char',
        templateIndex: 3,
    },
    {
        title: '实习地点',
        dataIndex: 'internship_position',
        editable: true,
        notNull: true,
        type: 'float',
        templateIndex: 4,
    },
    {
        title: '实习基地id',
        dataIndex: 'internship_base',
        editable: true,
        notNull: true,
        type: 'int',
        templateIndex: 5,
    },
    {
        title: '实习对象',
        dataIndex: 'internship_target',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 6,
    },
    {
        title: '计划学时',
        dataIndex: 'plan_hours',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 7,
    },
    {
        title: '学分',
        dataIndex: 'credit',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 8,
    },
    {
        title: '基数',
        dataIndex: 'cardinal_num',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 9,
    },
    {
        title: '工作量',
        dataIndex: 'workload',
        editable: true,
        notNull: false,
        type: 'float',
        templateIndex: 10,
    },
    {
        title: '备注',
        dataIndex: 'remark',
        editable: true,
        notNull: false,
        type: 'char',
        templateIndex: 12,
    },
]

// mock语句
// insert into textbook(textbook_type,textbook_name,textbook_publisher,director_job_id,member,publish_time,is_excellent,remark,performance_scroe,bonus,workload) values('国家级','数据结构','西北大学出版社',20130069,'cf','2019/01/01','是','无备注',1,1,1);

