module.exports.columns = [
  {
    title: '课程名',
    dataIndex: 'course_name',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 0,
  },
  {
    title: '课程级别',
    dataIndex: 'course_level',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 1,
  },
  {
    title: '主持人姓名',
    dataIndex: 'teacher_name',
    editable: false,
    notNull: false,
    type: 'char',
    templateIndex: 2,
    sourceTable: 'teacher_tbl',
    primaryKey: 'job_id',
    foreignKey: 'job_id',
  },
  {
    title: '主持人工号',
    dataIndex: 'job_id',
    editable: true,
    notNull: true,
    type: 'int',
    templateIndex: 3,
  },
  {
    title: '参与人',
    dataIndex: 'member',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 4,
  },
  {
    title: '是否在线',
    dataIndex: 'is_online',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 6,
  },
  {
    title: '时间',
    dataIndex: 'time',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 5,
  },
  {
    title: '备注',
    dataIndex: 'remark',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 7,
  },
]

module.exports.rules = {
  tableType: 'MOOC',
  itemColumnName: 'course_name',
  ruleColumnName: 'course_level',
  columns: [
    {title: "课程级别", dataIndex: "course_level", editable: true},
    {title: "工作量", dataIndex: "workload", editable: true},
    {title: "绩效", dataIndex: "performance_score", editable: true},
    {title: "奖金", dataIndex: "bonus", editable: true},
  ]
}