module.exports.columns = [
  {
    title: '姓名',
    dataIndex: 'teacher_name',
    editable: false,
    notNull: false,
    type: 'char',
    templateIndex: 0,
    sourceTable: 'teacher_tbl',
    primaryKey: 'teacher_job_id',
    foreignKey: 'job_id',
  },
  {
    title: '工号',
    dataIndex: 'teacher_job_id',
    editable: true,
    notNull: true,
    type: 'int',
    templateIndex: 1,
  },
  {
    title: '级别',
    dataIndex: 'level',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 2,
  },
  {
    title: '获批时间',
    dataIndex: 'win_time',
    editable: true,
    notNull: true,
    type: 'char',
    templateIndex: 3,
  },
  {
    title: '备注',
    dataIndex: 'remark',
    editable: true,
    notNull: false,
    type: 'char',
    templateIndex: 4,
  },
  {
    title: '绩效计分',
    dataIndex: 'performance_scroe',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 5,
  },
  {
    title: '奖金',
    dataIndex: 'bonus',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 6,
  },
  {
    title: '工作量',
    dataIndex: 'workload',
    editable: true,
    notNull: false,
    type: 'float',
    templateIndex: 7,
  }, 
]